# Generated by Django 4.1 on 2024-01-21 23:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOfPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('name_1', models.CharField(default='', max_length=20, null=True)),
                ('name_2', models.CharField(default='', max_length=20, null=True)),
                ('income', models.IntegerField(default=0)),
                ('rent', models.IntegerField(default=0)),
                ('water_supply', models.IntegerField(default=0)),
                ('gas', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=0)),
                ('food_expenses', models.IntegerField(default=0)),
                ('communication_expenses', models.IntegerField(default=0)),
                ('transportation_expenses', models.IntegerField(default=0)),
                ('insurance_fee', models.IntegerField(default=0)),
                ('daily_necessities', models.IntegerField(default=0)),
                ('medical_bills', models.IntegerField(default=0)),
                ('entertainment_expenses', models.IntegerField(default=0)),
                ('saving', models.IntegerField(default=0)),
                ('add_item', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BalanceOfPayments',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('year_month', models.CharField(max_length=7)),
                ('saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_for_balance', to='household_budget.balanceofpayments')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savings',
            },
        ),
        migrations.CreateModel(
            name='Goal_Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('savings_goal', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal_saving',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('rent_budget', models.IntegerField(default=0)),
                ('water_supply_budget', models.IntegerField(default=0)),
                ('gas_budget', models.IntegerField(default=0)),
                ('electricity_budget', models.IntegerField(default=0)),
                ('food_expenses_budget', models.IntegerField(default=0)),
                ('communication_expenses_budget', models.IntegerField(default=0)),
                ('transportation_expenses_budget', models.IntegerField(default=0)),
                ('insurance_fee_budget', models.IntegerField(default=0)),
                ('daily_necessities_budget', models.IntegerField(default=0)),
                ('medical_bills_budget', models.IntegerField(default=0)),
                ('entertainment_expenses_budget', models.IntegerField(default=0)),
                ('saving_budget', models.IntegerField(default=0)),
                ('add_item_budget', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Budget',
            },
        ),
    ]
