# Generated by Django 4.1 on 2024-01-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='amount',
        ),
    ]
