# Generated by Django 4.1 on 2024-01-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
