# Generated by Django 4.1 on 2024-01-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0002_remove_saving_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
