# Generated by Django 4.1 on 2024-01-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0002_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
