# Generated by Django 4.1 on 2024-01-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0003_saving_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='saving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_for_balance', to='household_budget.balanceofpayments'),
        ),
    ]
