# Generated by Django 4.1 on 2024-01-22 12:01

from django.db import migrations
import django.utils.timezone
import household_budget.models


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0004_alter_saving_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_saving',
            name='month',
            field=household_budget.models.MonthField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
