# Generated by Django 4.1 on 2024-01-22 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0006_alter_goal_saving_month_alter_goal_saving_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_saving',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
