# Generated by Django 4.1 on 2024-01-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0009_saving'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
