# Generated by Django 4.1 on 2024-01-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0012_paymentdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceofpayments',
            name='payment_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='household_budget.paymentdestination'),
        ),
    ]
