# Generated by Django 4.1 on 2024-01-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household_budget', '0013_balanceofpayments_payment_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdestination',
            name='user',
        ),
    ]
